export const exams = [
  {
    id: "ap",
    name: "応用情報技術者試験",
    shortName: "AP",
    description: "ITエンジニアの登竜門。技術からマネジメント・戦略まで幅広く問う（午前）",
    // IPA公式シラバスの中分類（23）。弱点分析はこの中分類＋genre（系）で集計する。
    categories: [
      "基礎理論",
      "アルゴリズムとプログラミング",
      "コンピュータ構成要素",
      "システム構成要素",
      "ソフトウェア",
      "ハードウェア",
      "ユーザーインタフェース",
      "情報メディア",
      "データベース",
      "ネットワーク",
      "セキュリティ",
      "システム開発技術",
      "ソフトウェア開発管理技術",
      "プロジェクトマネジメント",
      "サービスマネジメント",
      "システム監査",
      "システム戦略",
      "システム企画",
      "経営戦略マネジメント",
      "技術戦略マネジメント",
      "ビジネスインダストリ",
      "企業活動",
      "法務",
    ],
    color: "from-sky-500 to-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    textColor: "text-sky-600",
    badgeBg: "bg-sky-100",
  },
  {
    id: "fe",
    name: "基本情報技術者試験",
    shortName: "FE",
    description: "ITの基礎を証明する人気の国家試験。IT業界への第一歩（科目A）",
    categories: [
      "基礎理論",
      "アルゴリズムとプログラミング",
      "コンピュータ構成・ハードウェア",
      "ソフトウェア・OS",
      "データベース",
      "ネットワーク",
      "セキュリティ",
      "システム開発",
      "マネジメント",
      "ストラテジ・経営",
    ],
    color: "from-violet-500 to-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    textColor: "text-violet-600",
    badgeBg: "bg-violet-100",
  },
  {
    id: "ip",
    name: "ITパスポート試験",
    shortName: "IP",
    description: "社会人の必須教養。IT・経営・マネジメントの基礎を幅広く問う入門資格",
    categories: [
      "ストラテジ系（経営全般）",
      "マネジメント系（IT管理）",
      "テクノロジ系（IT技術）",
      "セキュリティ",
      "ネットワーク",
      "データベース",
      "経営戦略・法務",
      "プロジェクトマネジメント",
    ],
    color: "from-pink-500 to-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    textColor: "text-pink-600",
    badgeBg: "bg-pink-100",
  },
  {
    id: "am1",
    name: "午前Ⅰ（高度共通）",
    shortName: "午前Ⅰ",
    description: "全高度区分で共通の午前Ⅰ。テクノロジ・マネジメント・ストラテジを幅広く問う",
    categories: [
      "基礎理論",
      "アルゴリズムとプログラミング",
      "コンピュータ構成・システム",
      "データベース",
      "ネットワーク",
      "セキュリティ",
      "システム開発技術",
      "プロジェクト・サービスマネジメント",
      "システム戦略・経営戦略",
      "企業活動・法務",
    ],
    color: "from-indigo-500 to-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    textColor: "text-indigo-600",
    badgeBg: "bg-indigo-100",
  },
  {
    id: "pm",
    name: "プロジェクトマネージャ試験",
    shortName: "PM",
    description: "プロジェクト計画・管理・リーダーシップを問う高度試験",
    categories: [
      "プロジェクト統合マネジメント",
      "プロジェクトスコープマネジメント",
      "プロジェクトスケジュールマネジメント",
      "プロジェクトコストマネジメント",
      "プロジェクト品質マネジメント",
      "プロジェクト資源マネジメント",
      "プロジェクトリスクマネジメント",
      "プロジェクト調達マネジメント",
      "プロジェクトコミュニケーションマネジメント",
      "プロジェクトステークホルダマネジメント",
    ],
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    textColor: "text-blue-600",
    badgeBg: "bg-blue-100",
  },
  {
    id: "sc",
    name: "情報処理安全確保支援士試験",
    shortName: "SC",
    description: "セキュリティ設計・実装・管理を問う高度試験",
    categories: [
      "情報セキュリティ管理",
      "情報セキュリティ対策",
      "セキュリティ技術評価",
      "暗号技術",
      "認証・認可技術",
      "ネットワークセキュリティ",
      "アプリケーションセキュリティ",
      "インシデント対応・フォレンジクス",
    ],
    color: "from-red-500 to-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    textColor: "text-red-600",
    badgeBg: "bg-red-100",
  },
  {
    id: "st",
    name: "ITストラテジスト試験",
    shortName: "ST",
    description: "IT戦略立案・経営課題解決を問う高度試験",
    categories: [
      "経営戦略マネジメント",
      "技術戦略マネジメント",
      "ビジネスインダストリ",
      "システム戦略",
      "システム企画",
      "業務改革（BPR）",
      "ソリューションビジネス",
      "経営分析・財務",
    ],
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    textColor: "text-purple-600",
    badgeBg: "bg-purple-100",
  },
  {
    id: "nw",
    name: "ネットワークスペシャリスト試験",
    shortName: "NW",
    description: "ネットワーク設計・構築・運用を問う高度試験",
    categories: [
      "ネットワークアーキテクチャ",
      "データリンク層技術",
      "ネットワーク層技術（IP・ルーティング）",
      "トランスポート層・アプリケーション層",
      "ネットワーク管理・運用",
      "ネットワークセキュリティ",
      "無線LAN",
      "クラウドネットワーク",
    ],
    color: "from-green-500 to-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    textColor: "text-green-600",
    badgeBg: "bg-green-100",
  },
  {
    id: "db",
    name: "データベーススペシャリスト試験",
    shortName: "DB",
    description: "DB設計・SQL・パフォーマンスチューニングを問う高度試験",
    categories: [
      "データベース方式",
      "データモデリング・正規化",
      "関係データベース設計",
      "SQL（問合せ・更新・定義）",
      "トランザクション管理・排他制御",
      "障害回復",
      "データベース性能チューニング",
      "分散データベース・NoSQL",
    ],
    color: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    textColor: "text-orange-600",
    badgeBg: "bg-orange-100",
  },
  {
    id: "sa",
    name: "システムアーキテクト試験",
    shortName: "SA",
    description: "システム設計・アーキテクチャ選定を問う高度試験",
    categories: [
      "要件定義",
      "システム方式設計",
      "ソフトウェアアーキテクチャ設計",
      "信頼性・可用性設計",
      "性能・スケーラビリティ設計",
      "セキュリティアーキテクチャ",
      "システム移行計画",
      "テスト計画・評価",
    ],
    color: "from-teal-500 to-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    textColor: "text-teal-600",
    badgeBg: "bg-teal-100",
  },
  {
    id: "sm",
    name: "ITサービスマネージャ試験",
    shortName: "SM",
    description: "ITサービスの運用・管理・改善を問う高度試験",
    categories: [
      "サービスレベル管理（SLA）",
      "インシデント管理",
      "問題管理",
      "変更管理・リリース管理",
      "構成管理・資産管理",
      "キャパシティ管理",
      "可用性管理",
      "ITサービス継続管理",
    ],
    color: "from-cyan-500 to-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    textColor: "text-cyan-600",
    badgeBg: "bg-cyan-100",
  },
  {
    id: "au",
    name: "システム監査技術者試験",
    shortName: "AU",
    description: "ITシステムの監査・評価・リスク管理を問う高度試験",
    categories: [
      "システム監査計画",
      "システム監査実施",
      "システム監査報告・フォローアップ",
      "内部統制（IT全般統制）",
      "IT業務処理統制",
      "情報セキュリティ監査",
      "リスクアセスメント",
      "個人情報保護・法令対応",
    ],
    color: "from-slate-500 to-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    textColor: "text-slate-600",
    badgeBg: "bg-slate-100",
  },
];

// 試験のグルーピング（トップ＝初級、別ページ＝高度）
export const BASIC_EXAM_IDS = ["ip", "fe", "ap"] as const; // メイン（やさしい順：IP→FE→AP）
export const ADVANCED_EXAM_IDS = ["pm", "sc", "nw", "db", "sa", "st", "sm", "au"] as const; // 高度8区分

export const basicExams = BASIC_EXAM_IDS.map((id) => exams.find((e) => e.id === id)!);
export const advancedExams = ADVANCED_EXAM_IDS.map((id) => exams.find((e) => e.id === id)!);
export const am1Exam = exams.find((e) => e.id === "am1")!;

export function getExam(id: string) {
  return exams.find((e) => e.id === id);
}

// 問題ごとの正式な出典表記を生成する。
// 例(午前Ⅱ): 出典：IPA プロジェクトマネージャ試験 令和6年度 秋期 午前Ⅱ 問1
// 例(午前Ⅰ): 出典：IPA 高度情報処理技術者試験 午前Ⅰ（全区分共通） 令和6年度 春期 問1
// 試験区分ごとの「セクション表記」（出典に使う）。未指定は午前Ⅱ（高度）。
const SECTION_LABEL: Record<string, string> = {
  am1: "午前Ⅰ（全区分共通）",
  ap: "午前",
  fe: "科目A",
  ip: "", // ITパスポートは午前/午後の区別なし
};

export function questionSource(examId: string, year: string, qNumber?: number | null) {
  const q = qNumber ? ` 問${qNumber}` : "";
  if (examId === "am1") {
    return `出典：IPA 高度情報処理技術者試験 午前Ⅰ（全区分共通） ${year}${q}`;
  }
  const e = getExam(examId);
  if (examId in SECTION_LABEL) {
    const sec = SECTION_LABEL[examId];
    return `出典：IPA ${e?.name ?? ""} ${year}${sec ? ` ${sec}` : ""}${q}`;
  }
  return `出典：IPA ${e?.name ?? ""} ${year} 午前Ⅱ${q}`;
}
