export const exams = [
  {
    id: "pm",
    name: "プロジェクトマネージャ試験",
    shortName: "PM",
    description: "プロジェクト計画・管理・リーダーシップを問う高度試験",
    categories: [
      "プロジェクト統合マネジメント",
      "プロジェクトスコープマネジメント",
      "プロジェクトスケジュールマネジメント",
      "プロジェクトコストマネジメント",
      "プロジェクト品質マネジメント",
      "プロジェクトリスクマネジメント",
      "プロジェクト調達マネジメント",
      "プロジェクトコミュニケーションマネジメント",
    ],
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    textColor: "text-blue-600",
    badgeBg: "bg-blue-100",
  },
  {
    id: "sc",
    name: "情報処理安全確保支援士試験",
    shortName: "SC",
    description: "セキュリティ設計・実装・管理を問う高度試験",
    categories: [
      "情報セキュリティ管理",
      "情報セキュリティ対策",
      "セキュリティ技術評価",
      "暗号化技術",
      "認証・認可",
      "脆弱性管理",
      "インシデント対応",
      "セキュアプログラミング",
    ],
    color: "from-red-500 to-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    textColor: "text-red-600",
    badgeBg: "bg-red-100",
  },
  {
    id: "st",
    name: "ITストラテジスト試験",
    shortName: "ST",
    description: "IT戦略立案・経営課題解決を問う高度試験",
    categories: [
      "経営戦略マネジメント",
      "技術戦略マネジメント",
      "ビジネスインダストリ",
      "システム戦略",
      "システム企画",
      "業務改革（BPR）",
      "経営分析・財務",
    ],
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    textColor: "text-purple-600",
    badgeBg: "bg-purple-100",
  },
  {
    id: "nw",
    name: "ネットワークスペシャリスト試験",
    shortName: "NW",
    description: "ネットワーク設計・構築・運用を問う高度試験",
    categories: [
      "ネットワークアーキテクチャ",
      "データリンク層・ネットワーク層",
      "トランスポート層・アプリケーション層",
      "TCP/IPプロトコル",
      "ルーティング・スイッチング",
      "無線LAN",
      "ネットワークセキュリティ",
      "クラウドネットワーク",
    ],
    color: "from-green-500 to-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    textColor: "text-green-600",
    badgeBg: "bg-green-100",
  },
  {
    id: "db",
    name: "データベーススペシャリスト試験",
    shortName: "DB",
    description: "DB設計・SQL・パフォーマンスチューニングを問う高度試験",
    categories: [
      "データモデリング・正規化",
      "関係データベース設計",
      "SQL（問合せ・更新）",
      "トランザクション管理・排他制御",
      "障害回復",
      "データベース性能チューニング",
      "分散データベース",
      "NoSQL・データウェアハウス",
    ],
    color: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    textColor: "text-orange-600",
    badgeBg: "bg-orange-100",
  },
  {
    id: "sa",
    name: "システムアーキテクト試験",
    shortName: "SA",
    description: "システム設計・アーキテクチャ選定を問う高度試験",
    categories: [
      "要件定義",
      "システムアーキテクチャ設計",
      "ソフトウェアアーキテクチャ設計",
      "信頼性・可用性設計",
      "性能設計",
      "セキュリティアーキテクチャ",
      "システム移行計画",
      "テスト計画・評価",
    ],
    color: "from-teal-500 to-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    textColor: "text-teal-600",
    badgeBg: "bg-teal-100",
  },
  {
    id: "sm",
    name: "ITサービスマネージャ試験",
    shortName: "SM",
    description: "ITサービスの運用・管理・改善を問う高度試験",
    categories: [
      "サービスレベル管理（SLA）",
      "サービスデスク・インシデント管理",
      "問題管理",
      "変更管理・リリース管理",
      "構成管理・資産管理",
      "キャパシティ管理",
      "可用性管理",
      "ITサービス継続管理",
    ],
    color: "from-cyan-500 to-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    textColor: "text-cyan-600",
    badgeBg: "bg-cyan-100",
  },
  {
    id: "au",
    name: "システム監査技術者試験",
    shortName: "AU",
    description: "ITシステムの監査・評価・リスク管理を問う高度試験",
    categories: [
      "システム監査計画",
      "システム監査実施",
      "システム監査報告・フォローアップ",
      "内部統制（IT全般統制・IT業務処理統制）",
      "情報セキュリティ監査",
      "リスクアセスメント",
      "コンプライアンス監査",
      "個人情報保護・法令対応",
    ],
    color: "from-slate-500 to-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    textColor: "text-slate-600",
    badgeBg: "bg-slate-100",
  },
];

export function getExam(id: string) {
  return exams.find((e) => e.id === id);
}
